# Generated by Django 4.2.7 on 2023-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='')),
                ('fecha_servicio', models.DateField(verbose_name='')),
                ('cliente', models.CharField(max_length=30)),
                ('sevicio', models.TextField()),
                ('empleado', models.CharField(max_length=30)),
                ('cordinador', models.CharField(max_length=30)),
            ],
        ),
    ]
