# Generated by Django 5.0 on 2023-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
