# Generated by Django 5.0 on 2023-12-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas_servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaservicio',
            old_name='cordinador',
            new_name='coordinador',
        ),
        migrations.RenameField(
            model_name='reservaservicio',
            old_name='sevicio',
            new_name='servicio',
        ),
    ]
