# Generated by Django 4.2.7 on 2023-12-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0001_initial'),
        ('app_servicio', '0002_alter_servicio_descripcion'),
        ('app_empleados', '0001_initial'),
        ('app_coordinadores', '0001_initial'),
        ('app_reservas_servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservicio',
            name='cordinador',
        ),
        migrations.RemoveField(
            model_name='reservaservicio',
            name='sevicio',
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='coordinador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_coordinadores.coordinador'),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_empleados.empleado'),
        ),
    ]
