# Generated by Django 4.2.7 on 2023-11-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0002_coordinador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinador',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
